-- ============================================================
-- Balance Transfer Application - Oracle Database Schema
-- Creates the DAILY_BALANCES and KEY_CONFIGURATION tables
-- for tracking daily balance transfers across multiple keys.
-- ============================================================

-- KEY_CONFIGURATION: Stores configurable key names for the 16 key columns.
-- This allows dynamic labeling of KEY_1..KEY_16 in the UI and reports.
CREATE TABLE KEY_CONFIGURATION (
    KEY_ID          NUMBER(2)       NOT NULL,
    KEY_NAME        VARCHAR2(100)   NOT NULL,
    KEY_DESCRIPTION VARCHAR2(500),
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_DATE    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_KEY_CONFIGURATION PRIMARY KEY (KEY_ID),
    CONSTRAINT CHK_KEY_ID_RANGE CHECK (KEY_ID BETWEEN 1 AND 16)
);

-- DAILY_BALANCES: Main table storing daily balance data.
-- Each row represents one balance record identified by up to 16 configurable keys,
-- a year/month, and daily balance columns (DAY_0 = previous month end, DAY_1..DAY_31).
CREATE TABLE DAILY_BALANCES (
    BALANCE_ID      NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    KEY_1           VARCHAR2(100)   NOT NULL,
    KEY_2           VARCHAR2(100),
    KEY_3           VARCHAR2(100),
    KEY_4           VARCHAR2(100),
    KEY_5           VARCHAR2(100),
    KEY_6           VARCHAR2(100),
    KEY_7           VARCHAR2(100),
    KEY_8           VARCHAR2(100),
    KEY_9           VARCHAR2(100),
    KEY_10          VARCHAR2(100),
    KEY_11          VARCHAR2(100),
    KEY_12          VARCHAR2(100),
    KEY_13          VARCHAR2(100),
    KEY_14          VARCHAR2(100),
    KEY_15          VARCHAR2(100),
    KEY_16          VARCHAR2(100),
    BALANCE_YEAR    NUMBER(4)       NOT NULL,
    BALANCE_MONTH   NUMBER(2)       NOT NULL CHECK (BALANCE_MONTH BETWEEN 1 AND 12),
    DAY_0_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_1_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_2_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_3_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_4_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_5_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_6_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_7_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_8_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_9_BALANCE   NUMBER(18,2)    DEFAULT 0,
    DAY_10_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_11_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_12_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_13_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_14_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_15_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_16_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_17_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_18_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_19_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_20_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_21_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_22_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_23_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_24_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_25_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_26_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_27_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_28_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_29_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_30_BALANCE  NUMBER(18,2)    DEFAULT 0,
    DAY_31_BALANCE  NUMBER(18,2)    DEFAULT 0,
    CREATED_DATE    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_BALANCE_YEAR CHECK (BALANCE_YEAR BETWEEN 2000 AND 2100)
);

-- Indexes for common query patterns
CREATE INDEX IDX_DAILY_BAL_KEY1 ON DAILY_BALANCES (KEY_1);
CREATE INDEX IDX_DAILY_BAL_YEAR_MONTH ON DAILY_BALANCES (BALANCE_YEAR, BALANCE_MONTH);
CREATE INDEX IDX_DAILY_BAL_KEY1_YEAR_MONTH ON DAILY_BALANCES (KEY_1, BALANCE_YEAR, BALANCE_MONTH);
